/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.registration.form;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;


/**
 *
 * @author lincm
 */
public class Registration extends javax.swing.JFrame {
    
    Connection connection;
    Statement statement;
    String query;
    String cs;
    String user;
    String password;
    ResultSet resultset;
    String picturepath;
    
    /**
     * Creates new form Registration
     */
    public Registration() {
        
        connection = null;
        statement = null;
        query = null;
        resultset = null;
        user= "root";
        password = "";
        cs = "jdbc:mysql://localhost:3306/registration_form";
        initComponents();
        registerDriver();
    }
    
    public void registerDriver(){
    try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        connection = DriverManager.getConnection(cs, user, password);
        statement = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        resultset = statement.executeQuery("SELECT * FROM STUDENTS");
    }
    catch(SQLException ex){
            ex.printStackTrace();
        }
        
        catch (ClassNotFoundException e){
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtsex = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        txtregno = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtmale = new javax.swing.JRadioButton();
        txtfemale = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtdate = new com.toedter.calendar.JDateChooser();
        txtimagepath = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtlname = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setName("MUST"); // NOI18N

        jLabel1.setText("First Name");

        jLabel2.setText("RegNo");

        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtsex.add(txtmale);
        txtmale.setText("Male");

        txtsex.add(txtfemale);
        txtfemale.setText("Female");

        jLabel3.setText("Sex");

        jButton4.setText("First");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Previous");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("next");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("last");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel4.setText("D.O.B");

        txtdate.setDateFormatString("yyyy-MM-dd");

        txtimagepath.setBackground(new java.awt.Color(51, 255, 255));
        txtimagepath.setAutoscrolls(true);
        txtimagepath.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton3.setText("Image");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setText("Last Name");

        txtlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlnameActionPerformed(evt);
            }
        });

        jButton8.setText("Reset");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(27, 27, 27)
                                            .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(txtmale)
                                            .addGap(27, 27, 27)
                                            .addComponent(txtfemale)))
                                    .addGap(70, 70, 70)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtregno, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtimagepath, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtregno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmale)
                            .addComponent(txtfemale)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtimagepath, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//             query = "select * from students ";
//            resultset = statement.executeQuery(query);
            
            String regno = txtregno.getText(); 
            String fname = txtfname.getText();
            String lname = txtlname.getText(); 
            String sex = "";
            Date date = txtdate.getDate() ;
                    
            //converting date to be formatted and stored as a string 
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            String strDate = formatter.format(date);
            
            
            if (txtmale.isSelected()){
                sex = "M";
            }
            
            else{
                sex = "F";
            }
               if (fname.isEmpty()){
                   JOptionPane.showMessageDialog(null, "Enter your first name");
                   txtfname.requestFocus();
               }   
               else if(lname.isEmpty()){
                    JOptionPane.showMessageDialog(null, "Enter your last  name");
                    txtlname.requestFocus();
               }
               else if(regno.isEmpty()){
                   JOptionPane.showMessageDialog(null, "Enter your regno");
                    txtregno.requestFocus();
               }
               else if(sex.isEmpty()){
                   JOptionPane.showMessageDialog(null, "select your gender");
                   
               }
               else if(txtdate.getDate() == null){
                   JOptionPane.showMessageDialog(null, "Enter your birthday");
                   txtdate.requestFocus();
               }
            
               else{
                   try{
                       query = "insert into students(regno, first_name, last_name, sex, date_of_birth, image) VALUES('"+regno+"' ,'"+fname+"' ,'"+lname+"' ,'"+sex+"' ,'"+strDate+"', '"+picturepath+"'  )";
                       statement.executeUpdate(query);
                       JOptionPane.showMessageDialog(null, "record saved");
                       txtregno.setText("");
                       txtfname.setText("");
                       txtlname.setText("");
                       picturepath = "";
                       txtimagepath.setIcon(new ImageIcon(picturepath));
                       txtsex.clearSelection();
                       txtdate.setDate(null);
                       txtregno.setText("");
                       txtimagepath.setText("");
                       txtfname.requestFocus();
                         
                resultset = statement.executeQuery("SELECT * FROM STUDENTS");
                       
                   }
                   catch(SQLException ex)
                   {
                       ex.printStackTrace();
                   }
               }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
    
    }//GEN-LAST:event_txtfnameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         String imagepath = "";                         //initialise image path as a string
         JFileChooser chooser = new JFileChooser();     //create a file chooser 
         int choice = chooser.showOpenDialog(null);     //opens a jfile chooser dialogebox
         
         if (choice == JFileChooser.APPROVE_OPTION){    //if  we press ok on the file chooser 
             File file = chooser.getSelectedFile();     //file ssaves our chosen file 
             imagepath = file.getAbsolutePath();        //method gets the path of the chosen file and sacves it in the variable imagepath
             imagepath = imagepath.replace("\\", "/");  // finds "\\" and replaces it with /
         }
         ImageIcon icon = new  ImageIcon(imagepath);
         Image image = icon.getImage().getScaledInstance(txtimagepath.getWidth(), txtimagepath.getHeight(), Image.SCALE_SMOOTH); //auto scales the image
         txtimagepath.setIcon(new ImageIcon(image));
         picturepath = imagepath;
      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           String regno = txtregno.getText(); 
           
        try{  
                 
                if(txtregno.getText().isEmpty()){
                     JOptionPane.showMessageDialog(null, "Please insert the regno for te record you want to delete");
                     txtregno.requestFocus();
                 }
                else{
                 query = "delete from students where regno = '" +regno+ "' ";
                 int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this record?", "confirm", JOptionPane.YES_NO_CANCEL_OPTION);
                 if(response == JOptionPane.YES_OPTION){
                     JOptionPane.showMessageDialog(null, "record deleted");
                    statement.executeUpdate(query);
                 }
                 if(response == JOptionPane.NO_OPTION){
                     JOptionPane.showMessageDialog(null, "operation canceled");
                    
                 }
                 resultset = statement.executeQuery("SELECT * FROM STUDENTS");
             }
        }
       catch(SQLException ex)
           {
               ex.printStackTrace();
           }
               
                
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            String sex = null ;
            String image = null;
           
        try{
           
             if (resultset.first()){
                 String path = resultset.getString("image");
                 ImageIcon icon = new ImageIcon(path);
                 Image scaled = icon.getImage().getScaledInstance(txtimagepath.getWidth(), txtimagepath.getHeight(), Image.SCALE_SMOOTH);
                 
                 txtfname.setText(resultset.getString("first_name"));
                 txtlname.setText(resultset.getString("last_name"));
                 txtregno.setText(resultset.getString("regno"));
                 txtdate.setDate(resultset.getDate("date_of_birth"));
                 txtimagepath.setIcon(new ImageIcon(scaled));
                
                 if(resultset.getString("sex").equals("M") ){
                 txtmale.setSelected(true);
                 }
                 else{
                 txtfemale.setSelected(true); 
                 }
                 
             }
         }
          catch(SQLException ex)
           {
               ex.printStackTrace();
           }  
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
            String sex = null ;
            String image = null;
            boolean value = false;
            
        try{
            
                     if (resultset.next()){
                     String path = resultset.getString("image");
                     ImageIcon icon = new ImageIcon(path);
                     Image scaled = icon.getImage().getScaledInstance(txtimagepath.getWidth(), txtimagepath.getHeight(), Image.SCALE_SMOOTH);
                     txtfname.setText(resultset.getString("first_name"));
                     txtlname.setText(resultset.getString("last_name"));
                     txtregno.setText(resultset.getString("regno"));
                     txtdate.setDate(resultset.getDate("date_of_birth"));
                     txtimagepath.setIcon(new ImageIcon(scaled));
                     
                     if(resultset.getString("sex").equals("M") ){
                         txtmale.setSelected(true);
                     }
                     else{
                         txtfemale.setSelected(true);
                     }
         }}
          catch(SQLException ex)
           {
               ex.printStackTrace();
           }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
            String sex = null ;
            String image = null;

        try{
  
             if (resultset.last()){
                 String path = resultset.getString("image");
                 ImageIcon icon = new ImageIcon(path);
                 Image scaled = icon.getImage().getScaledInstance(txtimagepath.getWidth(), txtimagepath.getHeight(), Image.SCALE_SMOOTH);
                 txtfname.setText(resultset.getString("first_name"));
                 txtlname.setText(resultset.getString("last_name"));
                 txtregno.setText(resultset.getString("regno"));
                 txtdate.setDate(resultset.getDate("date_of_birth"));
                 txtimagepath.setIcon(new ImageIcon(scaled));
                 
                 if(resultset.getString("sex").equals("M") ){
                 txtmale.setSelected(true);
                 }
                 else{
                 txtfemale.setSelected(true); 
                 }
             }
         }
          catch(SQLException ex)
           {
               ex.printStackTrace();
           }                    
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
              String sex = null ;
            String image = null;
        try{
     
                 if (resultset.previous()){
                     String path = resultset.getString("image");
                     ImageIcon icon = new ImageIcon(path);
                     Image scaled = icon.getImage().getScaledInstance(txtimagepath.getWidth(), txtimagepath.getHeight(), Image.SCALE_SMOOTH);
                     txtfname.setText(resultset.getString("first_name"));
                     txtlname.setText(resultset.getString("last_name"));
                     txtregno.setText(resultset.getString("regno"));
                     txtdate.setDate(resultset.getDate("date_of_birth"));
                     txtimagepath.setIcon(new ImageIcon(scaled));
                     if(resultset.getString("sex").equals("M") ){
                         txtmale.setSelected(true);
                     }
                     else{
                         txtfemale.setSelected(true);
                     }
                     
//                  else{
//                        JOptionPane.showMessageDialog(null, "This is the first record");     
//                     }
                     
                     
                }
         }
          catch(SQLException ex)
           {
               ex.printStackTrace();
           }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
                     txtfname.setText(null);
                     txtlname.setText(null);
                     txtregno.setText(null);
                     txtdate.setDate(null);
                     txtimagepath.setIcon(null);
                     txtmale.setSelected(false);
                     txtfemale.setSelected(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JRadioButton txtfemale;
    private javax.swing.JTextField txtfname;
    private javax.swing.JLabel txtimagepath;
    private javax.swing.JTextField txtlname;
    private javax.swing.JRadioButton txtmale;
    private javax.swing.JTextField txtregno;
    private javax.swing.ButtonGroup txtsex;
    // End of variables declaration//GEN-END:variables
}
